### ISSUE TITLE
Adding xmc0: support

### ISSUE THREAD

**Issue by Rameron** [TheOfficialFloW/Adrenaline#253] opened 2018-07-02 08:45 UTC
Hello.

Is it possible to add the support of xmc0: partion in Adrenaline settings (mount point of Vita Memory Card in VItaShell)?

P.S. There are not vitasd drivers for simultaneously using Vita Memory Card and SD Card for 3.68 now.
P. S. S. I hope xmc0: mount point isn't exist only in VitaShell....

Thanks.

**Comment by Rameron** [comment] 2018-07-02 21:07
I was trying to modify the version of gamesd driver of [aagallag](https://github.com/aagallag/gamecard-microsd) (just added few lines for support of 3.68). But I cannot build that. Even without any changes of original code. There are tons of errors like implicit function declaration. For example "ksceKernelRegisterSuspendCallback" or "ksceKernelDelayThread".

Could anyone help me?

**Comment by dude22072** [comment] 2018-07-02 21:47
This is a duplicate of #248

**Comment by Rameron** [comment] 2018-07-04 05:55
Anyway, it is unneccesary now. I was finally modified gamesd driver.

**Comment by akiba01** [comment] 2018-07-05 10:43
What do you mean whit "I was finally modified gamesd driver."

Is there a way to use xmc0?

**Comment by Rameron** [comment] 2018-07-05 13:48
No, I didn't find the way to use it. My gamesd driver mounted only sd-card as ux0: partition and my vita memory card was ignored. I found an option to use the memory vita card in VitaShell through mounting it as xmc: partition but we cannot use this partition in Adrenaline. After I upgraded gamesd driver to 3.68 support it can to mount the vita memory card too (as uma0: partition). So we can to use this partition in Adrenaline and this is enough for me.

**Comment by akiba01** [comment] 2018-07-05 14:10
Thanks for the answer. If isnt too much could you please explain how to do it?
I have gamesd 1.3 installed, do i have to mount the mc as uma0 using vitashell?

**Comment by Rameron** [comment] 2018-07-05 14:16
akiba01, you can just look it on my git. There is only one repository.

**Comment by akiba01** [comment] 2018-07-05 14:56
In ur0:tai i had:
gamesd.skprx 1.3 (3.68 compatible)
config.txt whit added line under KERNEL for gamesd
my sd2vita works perfectly fine as ux0

I have added your .cfg file whit "microsd=ux0 memorycard=uma0"
Do i have to add something else?  (CMakeLists.txt, main.c, exports.yml) ?

I have rebooted but in vitashell i dont see the memory card mounted as uma0 yet.

Sorry for this im a noob, and thanks again man

**Comment by akiba01** [comment] 2018-07-05 20:36
sd2vita acting weird after i removed it from the console i think.

**Comment by TheOfficialFloW** [comment] 2018-07-09 14:46
Will be available next update: https://github.com/TheOfficialFloW/Adrenaline/commit/3352186d332891770343865149a05f6d27a717b0

**Closed by TheOfficialFloW** 2018-07-09 14:46 UTC
